### ISSUE TITLE
Error with PHP 7.0

### ISSUE THREAD

**Issue by nemstaa** [wazum/pagetree-resizable#1]
Currently we are using PHP 7.0.
Therefore
[$version] = explode('.', VersionNumberUtility::getCurrentTypo3Version());
gives an error in DocumentTemplate.php.
I had to change it to
list($version) = explode('.', VersionNumberUtility::getCurrentTypo3Version());

**Comment by wazum** [comment]
Oh, shame on me ;-) Thanks for your report.
I fixed the issue and released a new version (1.1.2)

**Comment by nemstaa** [comment]
Thanks for your great work! ;-)
