### ISSUE TITLE
JS Error 8.7.24

### ISSUE THREAD

**Issue by sevensix** [wazum/pagetree-resizable#3]
Loaded the Master via git and installed the extension. When loading the Typo3 Backend The console  shows errors. Looks like it cant load the JS properly?
![pagetree](https://user-images.githubusercontent.com/4035097/54520359-cf9b5200-4968-11e9-810f-eff3f9072d72.JPG)

**Comment by wazum** [comment]
@sevensix can you show me the details on the first line of errors (404 not found)? What file fails loading?

**Comment by sevensix** [comment]
http://vt.sevensix.cc/typo3/TYPO3/CMS/PagetreeResizable/PagetreeResizable8.js?bust=982e63753922a0dabdfcd0d0b0189f2dccd269a3

**Comment by sevensix** [comment]
shouldn't this link link to the extensions Public JS folder?

**Comment by wazum** [comment]
That's right, the path is nonsense.
Would be nice if you could debug what's going on in `\TYPO3\CMS\Core\Page\PageRenderer::loadRequireJsModule` for this module.

**Comment by sevensix** [comment]
...using typo3 8.7.24 by the way

**Comment by sevensix** [comment]
I deinstalled the extension and removed it an reinstalled it. now it works... strange...so this topic can be closed
