### ISSUE TITLE
It does not seem to work with TYPO3 10.3

### ISSUE THREAD

**Issue by vicdev82** [wazum/pagetree-resizable#8]
The handle is not being shown. I installed the package with composer and installed it. Should it work out of the box or do I have to configure something?

**Comment by wazum** [comment]
@Vicdev882 No, should not work out of the box with 10.3, as stated in composer and ext_emconf it works up until 10.2. There have been deprecations and a convenient hook disappeared, so it's a bit of work to make this happen for >= 10.3. I'm on it, but only in my spare time.

**Comment by saitho** [comment]
Maybe it would be wise to include this into the TYPO3 10 core?

**Comment by wazum** [comment]
They accept no new features anymore and they deliberately removed it with 8, so I guess there's some reason for that. The extension has nearly 20 K installations, so it's no secret that this is desired.
Let's see if we get it into 11 then … :raising_hand:

**Comment by bmack** [comment]
In order to make it happen for v10, I suggest the following:

* Create a PSR-15 middleware for Backend and check for the route in the $request object and validate against "main" and the element browser popups.

If that is true, just executed the following code:

```
        $pageRenderer = GeneralUtility::makeInstance(PageRenderer::class);
        if ($width = $this->getUserPageTreeWidth()) {
            $pageRenderer->addCssInlineBlock('wazum/pagetree-resizable', '
            .scaffold-content-navigation-expanded .scaffold-content-navigation {
                width: ' . $width . 'px;
            }
            .scaffold-content-navigation-expanded .scaffold-content-module {
                left: ' . $width . 'px;
            }
        ');
        }

        $pageRenderer->addCssFile('EXT:pagetree_resizable/Resources/Public/Stylesheet/PagetreeResizable.css');
        $pageRenderer->loadRequireJsModule('TYPO3/CMS/PagetreeResizable/PagetreeResizable9');
```

I have a running version locally, in case you're interested.

**Comment by wazum** [comment]
@bmack  sure, thanks
